### ISSUE TITLE
关于真实地址

### ISSUE THREAD

**Issue by lizeming123** [wu67/my_aria2_conf#1]
虽然用抓包工具抓到了一些地址，但请问一般真实下载地址是怎样的。

比如有一个地址包含file这个关键字，但用这个地址应用到js里下载不出东西，而且也不符合作者本身所说“至少有4个”
但其它的地址又似乎太短

**Comment by wu67** [comment]
@lizeming123  
例子："https://nj02all01.baidupcs.com/file/eb8350170d9f0a6f5f098d39a3e16c75?bkt=p3-1400eb8350170d9f0a6f5f098d39a3e16c756ba2fe9700000fcd5e50&fid=895128782-250528-829392384501275&time=1490623082&sign=FDTAXGERBHS-DCb740ccc5511e5e8fedcff06b081203-10Yxm%2FoVmj0Ln4zqgG5%2FD%2B6EKAc%3D&to=69&size=265117264&sta_dx=265117264&sta_cs=1&sta_ft=rar&sta_ct=4&sta_mt=4&fm2=MH,Nanjing02,Netizen-anywhere,,guangdongct&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400eb8350170d9f0a6f5f098d39a3e16c756ba2fe9700000fcd5e50&expires=8h&rt=pr&r=567781155&mlogid=1992618430706890016&vuk=895128782&vbdid=-&fin=M.O.V.E.-.%5BGamble.Rumble%5D.%E5%8D%95%E6%9B%B2.%28APE%29.rar&bflag=69,79,80,8,19,1869&err_ver=1.0&check_blue=1&rtype=1&iv=0&dp-logid=1992618430706890016&dp-callid=0.1.1&hps=1&csl=240&csign=CAJCo%2F3DAL6dCX4IgS%2BKJW4Q%2Fwo%3D&by=themis",

以上地址就是一个压缩包的真实地址，它被包含在d.pcs.baidu.com这个域的查询结果的返回值（json）里面。

值得注意的是
- file这个关键字在链接里的出现形式为`******/file/*****`， 而不是 `******/pcs/file?*****`
- 在我看来，前者为真实地址，而后者则是一个查询性质的链接，包含的则是下载工具向这个域发送请求的参数，请求返回的信息才包含着真实下载地址
- 其实真实下载地址里也有部分参数是没用的，不过剔除起来挺麻烦的我就没理它了

**Comment by lizeming123** [comment]
那么我的确是抓到过真实地址，但有个问题就是，这种地址很少，而且从今晚开始我无论怎样下载都找不到，东西都下完了也就找到一些https://d.symcb.com/cps、https://www.digicert.com/CPS 之类的地址

就算是昨晚和今天上午我抓到过真实地址，但aria2下不了，提示凭证过期、无法加密等各种错误后就停止了

抓包方面我没什么经验，一般抓所有包然后找 https://  这个字符串，曾试过用 http.host contains "d.pcs.baidu.com" 来过滤显示，之前还算有用，但今晚我文件都下完了连一条都没看见，真的很无语

也试过用脚本获取直链，但应用到你的js后，返回https://allall01.baidupcs.comundefined

**Comment by wu67** [comment]
@lizeming123 很明显你这是找错了，根本就不是真实地址。建议你还是仔细看看抓包教程

**Comment by lizeming123** [comment]
但我能肯定我试过类似你所给出的真实地址的地址，确实是不行的。
除了你给出的n开头的，我还试过y开头的

**Comment by wu67** [comment]
@lizeming123 你到底是怎么抓地址的，说明详细一点嘛。用脚本站的直链脚本获取的不一定对，建议对百度云管家抓包。
我在mac平台下，用 Charles 随便找一个文件都能抓出至少4个。如果抓试用高速通道的地址速度更快，不过地址类型貌似有区别，我没仔细对比

**Comment by lizeming123** [comment]
wireshark ，用百度云管家下载，不过滤，抓所有包，字符串查找"https://"，找跟你所说差不多的链接

**Comment by lizeming123** [comment]
比如我刚刚抓到
 [truncated]Location: https://yqall02.baidupcs.com/file/a02125363ce27df3d95c8b1647d4bbff?bkt=p3-0000b4ebf6761f8ab26f02e254a67bbdb358&fid=1477350046-250528-298254430170493&time=1490710286&sign=FDTAXGERLBHS-DCb740ccc5511e5e8fedcff06b081203-D
虽说没你给那个那么长，但前面的格式是差不多吧

**Comment by wu67** [comment]
@lizeming123 格式是差不多，但链接参数少了起码三分之一，估计就是这部分导致的错误。要不你换其他版本的云管家试试呗，这我也没辙啊

**Comment by lizeming123** [comment]
@4thleaf 这是最新版的云管家了
昨天试了下你说的charles，发现只能抓到update.pan.baidu.com，今天出现了个pan.baidu.com，但里面全是乱码，真奇怪呀
既然你这边没问题，那剩下的我就自己努力吧，这两天承蒙关照了
