### ISSUE TITLE
macos添加开机启动项

### ISSUE THREAD

**Issue by jqtmviyu** [wu67/my_aria2_conf#4]
https://www.v2ex.com/t/338358

```sh
vim ~/Library/LaunchAgents/com.github.aria2.plist

===
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Label</key>
<string>com.github.aria2</string>
<key>RunAtLoad</key>
<true/>
<key>KeepAlive</key>
<false/>
<key>ProgramArguments</key>
<array>
<string>/usr/local/bin/aria2c</string>
</array>
<key>ServiceDescription</key>
<string>The ultra fast download utility</string>
</dict>
</plist>
===

launchctl load ~/Library/LaunchAgents/com.github.aria2.plist
```

**Comment by wu67** [comment]
感谢你的建议.

但其实目前版本不太合适.
因为目前最新的1.36版本, 在M系列的芯片上, 以静默状态运行(加-D参数), 在下载某些链接时整个程序会直接崩溃. 参考去年我发的issue: [aria2 issue#1962](https://github.com/aria2/aria2/issues/1962), 但是aria2至今一直都没有发布新版本, 也没有维护者回复issue.

所以 开机(静默)启动 这个行为目前在我看来是不太合适的, 很可能会让你的服务在无感知的情况下发生意料之外的行为.

目前个人建议是, 在Mac M系列芯片的机器上, iterm2固定开一个tab, 手动执行 `aria2c` 启动程序以提供服务, 这样即使程序崩溃了,   你也可能在对应的CLI界面看到明显的、程序停止运行的状态.

**Comment by jqtmviyu** [comment]
原来是这样. 我是intel 芯片😂
